spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/bible?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: jesusisking
  profiles:
    include: oauth

  jwt:
    secret: rksksehdnflfmfdlrlwldosdvvjzlsakepdldkstodrlsmsgustlfdmstlrndckdejrkdwjfgkrpcpdltmalehsdlskfmfcpdltmalehdspclsrnemfdms
